apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: grant
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/javicv/kubectl-grant/releases/download/v0.1.0/grant_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./grant"
      to: "."
    - from: LICENSE
      to: "."
    bin: "grant"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/javicv/kubectl-grant/releases/download/v0.1.0/grant_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./grant"
      to: "."
    - from: LICENSE
      to: "."
    bin: "grant"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/javicv/kubectl-grant/releases/download/v0.1.0/grant_windows_amd64.zip
    sha256: ""
    files:
    - from: "/grant.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "grant.exe"
  shortDescription: A new plugin
  homepage: https://github.com/javicv/kubectl-grant
  caveats: |
    Usage:
      $ kubectl grant

    For additional options:
      $ kubectl grant --help
      or https://github.com/javicv/kubectl-grant/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
